# Generated by Django 4.1.3 on 2022-12-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogcitoPython', '0003_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=300)),
                ('send_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
